language: node_js
node_js:
- 4
notifications:
  slack:
    secure: gwiwig22r2nwBwKJ+oLwmrcEz+NPTHZOJDD+HUyCOj4owFUwh+dIWZkPlesZz0STZRGeJFKHFi21SVCihCiS28T495O1QrGDfVpZCPMfUxC6CjC5MfS3mVXX9mpgmBhJdevixRXNndaArwx2zwsDF4/Btb3QoEtM1mJ6z9ccTc2inJRaee+eq7ogIc859rJDJ5h4jdcPCMpStDinF8+5CmEayWaZBfnrPA/ADQtdvyPXEeJ2fCslZKuzrpHHQxpXGRdZgNB/bSdFqYiLvdzalvrYhCFmmIpdvx9HvZlUyIDTOSr8QFC0IQfkdlCZyMbzP6nFJFPvYHr6z3nV8pwhHvw2qBiRVNB98h1AsKYx3CGB0ur9p/aRR+AOFFlI2IWgXy31PHEmt6a1p2aLNVQCTm6igxUOFbCJpDADCU7cYvqQir4LORZ5ZFlvsCmtEI951/x4/QdCRhAjH9jDoICz1s8zUhPAM9/qCIwAiXfxSMYXmDH2J2TB590JY6vf3dGQx889ev3YaSi19S3RrUdXF4blDYU9jb59JkACvt0WFVfSfWJFilH18kYvq9TUilMByQilceeSgj1EPkmvF0MggBoK1DgD+gIrAMfv1o2G5rzgwEXEddO7s04X2SdlZKhZw5DXsyiCTgUXm5xuQHc5ShQj6/T6SO8VNu5bom5NkP4=
