version: '2'

services:
  jumpline:
    extends:
      file: common.yml
      service: jumpline
    env_file: ../.env
    environment:
      NODE_ENV: production
    expose:
      - "3000"
    ports:
      - "3000:3000"
      - "3001:3001"
      - "8000:8000"
