version: '2'

services:
  jumpline:
    extends:
      file: common.yml
      service: jumpline
    build:
      args:
        # AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
        # AWS_SECRET_KEY: ${AWS_SECRET_KEY}
        # AWS_BUCKET: jumpline-assets-prod
        JUMPLINE_API_URL: https://hyz337t43k.execute-api.us-east-1.amazonaws.com/staging/graphql
        NODE_ENV: production
    env_file: .env-prod
    restart: always

  lb:
    image: 'dockercloud/haproxy:1.2.1'
    links:
      - jumpline-a
      - jumpline-b
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    restart: always

  logspout:
    image: 'gliderlabs/logspout'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    command: syslog://logs4.papertrailapp.com:52334

  jumpline-a:
    extends:
      service: jumpline

  jumpline-b:
    extends:
      service: jumpline
