version: '2'

services:
  jumpline:
    extends:
      file: common.yml
      service: jumpline
    environment:
      NODE_ENV: production
      IQUEUE_API_URL: https://api-staging.jumpline.me/graphql
      LOADERIO_TOKEN: loaderio-1d5629aba788b63738b1de7b1763a39f
    #logging:
    #  driver: syslog
    ports:
      - "80:8000"
    restart: always
