version: '2'

services:
  jumpline:
    extends:
      file: common.yml
      service: jumpline
    build:
      args:
        IQUEUE_API_URL: https://l38fle032c.execute-api.us-east-1.amazonaws.com/staging/graphql
        NODE_ENV: production
    environment:
      NODE_ENV: production
      LOADERIO_TOKEN: loaderio-2d1918d75ca5246201ff93f37f2604ed
      SLACK_WEBHOOK: ${SLACK_WEBHOOK}
    image: jumpline:${npm_config_tag_version_prefix}${npm_package_version}
    restart: always

  lb:
    image: 'dockercloud/haproxy:1.2.1'
    links:
      - jumpline-a
      - jumpline-b
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    restart: always

  logspout:
    image: 'gliderlabs/logspout'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    command: syslog://logs4.papertrailapp.com:52334

  jumpline-a:
    image: us.gcr.io/${GOOGLE_PROJECT_ID}/jumpline:${npm_config_tag_version_prefix}${npm_package_version}
    restart: always

  jumpline-b:
    image: us.gcr.io/${GOOGLE_PROJECT_ID}/jumpline:${npm_config_tag_version_prefix}${npm_package_version}
    restart: always
